[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_DISABLE_CSS_OPTIMIZATION = "true"

[functions]
  # Increase the function size limit (default is 10MB)
  included_files = ["**/*"]
  node_bundler = "esbuild"

# Split large functions if needed
[functions."___netlify-handler"]
  external_node_modules = ["@netlify/functions"]

# Optimize image handling
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Configure Netlify Image CDN for optimized images
[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true