[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=8192"
  NEXT_TELEMETRY_DISABLED = "1"
  PNPM_VERSION = "9.0.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Correct functions configuration
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Redirects for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Specify function-level configurations if needed
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"