[build]
  command = "pnpm install && pnpm run build && pnpm next export"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=8192"
  NEXT_TELEMETRY_DISABLED = "1"
  PNPM_VERSION = "9.0.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Correct functions configuration
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Cache control for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"