[build]
  command = "npm install --no-frozen-lockfile && NEXT_PUBLIC_NETLIFY_SITE=true npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/image"
  status = 200
  force = true