[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  PNPM_VERSION = "9.0.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Increase function timeout and memory
[functions]
  node_bundler = "esbuild"
  timeout = 30
  memory = 3008

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200